services:
  myapp:
    image: myapp:local
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/ibex
      cache_from:
        - type=gha

    container_name: myapp
    restart: unless-stopped

    env_file:
      - .env

    ports:
      - "3000:3000"

    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/ibex