// ============================================================
// CONSTANTS
// ============================================================

const DAY_KEYS = [
  "monday",
  "tuesday",
  "wednesday",
  "thursday",
  "friday",
  "saturday",
  "sunday",
];

const DAY_FIELD_KEYS = [
  "monday",
  "tuesday",
  "wednesday",
  "thursday",
  "friday",
  "saturday",
  "sunday",
];

const DAY_ABBR_MAP = {
  SUN: "sunday",
  MON: "monday",
  TUE: "tuesday",
  WED: "wednesday",
  THU: "thursday",
  FRI: "friday",
  SAT: "saturday",
};

const HEADER_ALIASES = {
  "vehicle type": "vehicleType",
  d: "vehicleType",
  vehicle: "vehicleType",
  vendor: "vendor",
  "vehicle entity": "vehicleEntityName",
  "vehicle reg": "vehicleReg",
  "vehicle registration": "vehicleReg",
  drivers: "drivers",
  "employee id": "employeeCode",
  "user name": "name",
  "off day": "offDay",
  campaign: "campaign",
  batch: "batch",
  entity: "entity",
  "shift timings": "shiftTiming",
  "office arival time": "officeArrivalTime",
  "office arrival time": "officeArrivalTime",
  "drop time": "dropTime",
  contact: "contact",
  area: "area",
  "sub area": "subArea",
  subarea: "subArea",
  block: "block",
  address: "address",
};

const MIN_REST_MINUTES = 8 * 60;
const DEFAULT_MAX_DAILY_HOURS = 12;
const DEFAULT_MAX_WEEKLY_HOURS = 60;
const PICKUP_LEAD_MINUTES = 2 * 60;
const SHIFT_TIME_ANCHOR_DATE = "1970-01-01";
const KARACHI_UTC_OFFSET_MINUTES = 5 * 60;
const ADDRESS_MATCH_THRESHOLD = 0.15;
const FALLBACK_ROUTE_CAPACITY = 10;

const DEFAULT_CAPACITY_BY_VEHICLE_TYPE = {
  CAR: 4,
  VAN: 12,
  HIJET: 10,
  KARVAN: 15,
  BUS: 40,
};

const VEHICLE_TYPES = new Set(["CAR", "VAN", "HIJET", "KARVAN", "BUS"]);

const VEHICLE_TYPE_ALIASES = {
  KARVAN: "KARVAN",
  KARVEN: "KARVAN",
  CAR: "CAR",
  VAN: "VAN",
  HIJET: "HIJET",
  "HI-JET": "HIJET",
  BUS: "BUS",
};

const ENTITY_VALUES = new Set(["IBEX", "VW"]);

const ADDRESS_STOPWORDS = new Set([
  "flat",
  "floor",
  "house",
  "street",
  "st",
  "no",
  "number",
  "near",
  "phase",
  "block",
  "society",
  "road",
  "karachi",
  "apartment",
  "apartments",
  "building",
  "plot",
  "the",
  "of",
  "and",
  "view",
  "town",
  "city",
  "sector",
  "area",
  "opposite",
  "behind",
  "infront",
  "front",
  "gali",
  "commercial",
]);

const AREA_ALIASES = {
  pechs: "P.E.C.H.S",
  "pechs,": "P.E.C.H.S",
  "6 pechs": "P.E.C.H.S",
  garden: "Garden East",
  "garden headquarters": "Garden East",
  "garden east": "Garden East",
  "garden east.": "Garden East",
  "garden east k": "Garden East",
  "garden west": "Garden West",
  "garden west,": "Garden West",
  nazimabad: "Nazimabad",
  "nazimabad karachi": "Nazimabad",
  naizamabad: "Nazimabad",
  naizmabad: "Nazimabad",
  nazimbad: "Nazimabad",
  nazaimabad: "Nazimabad",
  "nazaimabad no 4": "Nazimabad",
  "north nazimabad": "North Nazimabad",
  "n nazimabad": "North Nazimabad",
  "north nazimbad": "North Nazimabad",
  "north naizamabad": "North Nazimabad",
  "north naizamabad.": "North Nazimabad",
  "north naizmabad": "North Nazimabad",
  "north nazimbad": "North Nazimabad",
  bufferzone: "Buffer Zone",
  "bufferzone,": "Buffer Zone",
  "buffer zone": "Buffer Zone",
  "buffer zone.": "Buffer Zone",
  "2 minutes chowrangi": "2 Min Chowrangi",
  "2 minute chowrangi": "2 Min Chowrangi",
  "north karachi": "North Karachi",
  "north karach": "North Karachi",
  "north karachi.": "North Karachi",
  "noth karachi": "North Karachi",
  "fb area": "F.B Area",
  "f.b area": "F.B Area",
  "fb area.": "F.B Area",
  "federal b area": "F.B Area",
  liaqatabad: "Liaquatabad",
  "teen hatthi": "Teen Hatti",
  teenhati: "Teen Hatti",
  teenhatti: "Teen Hatti",
  "gulistan e johar": "Gulistan-e-Jauhar",
  "gulistan-e-johar": "Gulistan-e-Jauhar",
  johar: "Gulistan-e-Jauhar",
  jauhar: "Gulistan-e-Jauhar",
  "jauhar chowrangi": "Gulistan-e-Jauhar",
  "gulshan -e-iqbal": "Gulshan-e-Iqbal",
  "gulshan e iqbal": "Gulshan-e-Iqbal",
  gulshan: "Gulshan-e-Iqbal",
  "shah faisal": "Shah Faisal Colony",
  "shah faisal colony": "Shah Faisal Colony",
  "shah faisa": "Shah Faisal Colony",
  shahfaisal: "Shah Faisal Colony",
  mlir: "Shah Faisal Colony",
  malir: "Malir City",
  "malir cantt": "Malir Cantt",
  "malir cantt.": "Malir Cantt",
  "malir cant": "Malir Cantt",
  "malir count": "Malir Cantt",
  "malir cattle": "Malir Cantt",
  saudabad: "Saudabad",
  mehoodabad: "Mehmoodabad",
  mehmoodabad: "Mehmoodabad",
  mehmmodabad: "Mehmoodabad",
  mehmodabad: "Mehmoodabad",
  "mehmoodabad,": "Mehmoodabad",
  mehmdabad: "Mehmoodabad",
  mehmoodbad: "Mehmoodabad",
  "gulzar e hijr": "Gulzar-e-Hijri",
  "gulzar e hijri": "Gulzar-e-Hijri",
  "gulazar-e-hijri": "Gulzar-e-Hijri",
  "gulzar-e-hijr": "Gulzar-e-Hijri",
  "gulzar hijri": "Gulzar-e-Hijri",
  "gulzar e hijri,": "Gulzar-e-Hijri",
  "madrass chowrangi": "Gulzar-e-Hijri",
  "gulazar-e-hijri": "Gulzar-e-Hijri",
  dha: "Defence (DHA)",
  "dha phase 8": "Defence (DHA)",
  "dha phase 2": "Defence (DHA)",
  "defense view": "Defence (DHA)",
  "defence view": "Defence (DHA)",
  defense: "Defence (DHA)",
  defence: "Defence (DHA)",
  "phase 2": "Defence (DHA)",
  "phase 2 ext": "Defence (DHA)",
  "defence view.": "Defence (DHA)",
  clifton: "Clifton",
  "clifton,": "Clifton",
  "korangi crossing": "Korangi",
  crossing: "Korangi",
  "khalid bin waleed road": "Old City Area",
  saddar: "Old City Area",
  "saddar,": "Old City Area",
  "tibet center": "Old City Area",
  "m a jinnah road": "Old City Area",
  "ma jinnah road": "Old City Area",
  "m.a.jinnah road": "Old City Area",
  "scheme 33": "Scheme 33",
  "kaneez fatima": "Kaneez Fatima",
  maymaar: "Gulshan-e-Maymar",
  cantt: "Cantt",
  "cant station": "Cantt",
  "pib colony": "PIB Colony",
  pib: "PIB Colony",
  "jamshed road": "Jamshed Road",
  "jhamshed road": "Jamshed Road",
  "jamshad road": "Jamshed Road",
  "jamshad rd": "Jamshed Road",
  "jail road": "Jail Road",
  numaish: "Numaish",
  numish: "Numaish",
  nomaish: "Numaish",
  "soldier bazar": "Soldier Bazar",
  "soldier bazar no 2": "Soldier Bazar",
  "soldier bazar #1": "Soldier Bazar",
  "soldeir bazar # 1": "Soldier Bazar",
  "akhtar colony": "Akhtar Colony",
  "aktar clony": "Akhtar Colony",
  qayyumabad: "Qayyumabad",
  qayummabad: "Qayyumabad",
  qaiyumabad: "Qayyumabad",
  qyummabad: "Qayyumabad",
  bahadurabad: "Bahadurabad",
  bahadarabad: "Bahadurabad",
  bahadrubad: "Bahadurabad",
  bahardurabad: "Bahadurabad",
  "azam town": "Azam Town",
  "azam basti": "Azam Town",
  "azam basti,": "Azam Town",
  dalmia: "Dalmia",
  airport: "Airport",
  "khi airport": "Airport",
};

const BULK_UPLOAD_JOB_TTL_MS = 30 * 60 * 1000;
const MIN_BATCH_SIZE = 10;
const MAX_BATCH_SIZE = 1000;
const DEFAULT_BATCH_SIZE = 100;
const PENDING_WRITE_FLUSH_SIZE = 25;
const ROW_GROUP_CONCURRENCY = 24;
const BATCH_TX_TIMEOUT_MS = 20000;
const BATCH_TX_MAX_WAIT_MS = 10000;

module.exports = {
  DAY_KEYS,
  DAY_FIELD_KEYS,
  DAY_ABBR_MAP,
  HEADER_ALIASES,
  MIN_REST_MINUTES,
  DEFAULT_MAX_DAILY_HOURS,
  DEFAULT_MAX_WEEKLY_HOURS,
  PICKUP_LEAD_MINUTES,
  SHIFT_TIME_ANCHOR_DATE,
  KARACHI_UTC_OFFSET_MINUTES,
  ADDRESS_MATCH_THRESHOLD,
  FALLBACK_ROUTE_CAPACITY,
  DEFAULT_CAPACITY_BY_VEHICLE_TYPE,
  VEHICLE_TYPES,
  VEHICLE_TYPE_ALIASES,
  ENTITY_VALUES,
  ADDRESS_STOPWORDS,
  AREA_ALIASES,
  BULK_UPLOAD_JOB_TTL_MS,
  MIN_BATCH_SIZE,
  MAX_BATCH_SIZE,
  DEFAULT_BATCH_SIZE,
  PENDING_WRITE_FLUSH_SIZE,
  ROW_GROUP_CONCURRENCY,
  BATCH_TX_TIMEOUT_MS,
  BATCH_TX_MAX_WAIT_MS,
};